import { Inter } from "next/font/google";
import NavBar from "./components/Navbar";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tasks",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-200">
        {/* <NavBar /> */}
        {children}</body>
    </html>
  );
}
